sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - apache2
    - libapache2-mod-fastcgi
    - npm
language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
env:
  matrix:
    - MAGENTO_CE_VERSION=1.9.3.1
    - MAGENTO_CE_VERSION=1.9.2.4
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/node_modules
before_install: ./dev/travis/before_install.sh
install: true #composer install --no-interaction --no-dev --prefer-dist
before_script: true #./dev/travis/before_script.sh
script: true #./dev/travis/launch_tests.sh