sudo: required
dist: trusty
group: edge
language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
env:
  global:
    - COMPOSER_MODULE_NAME=bitbull/magento-tooso-search
  matrix:
    - MAGENTO_CE_VERSION=1.9.3.1
    - MAGENTO_CE_VERSION=1.9.2.4
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/node_modules
before_install: ./dev/travis/before_install.sh
install: ./dev/travis/install.sh
before_script: true #./dev/travis/before_script.sh
script: sleep 30 #./dev/travis/launch_tests.sh